[package]
name = "servokit-example-desktop-gpui"
version = "0.1.0"
edition = "2021"
publish = false

[[example]]
name = "shutdown"
path = "examples/shutdown.rs"

[dev-dependencies]
cocoa = "0.26"
objc = "0.2.7"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[dependencies]
zed_gpui = { package = "gpui", version = "0.2.2", features = ["runtime_shaders"] }
raw-window-handle = "0.6.2"
servokit = { path = "../../crates/servokit", features = ["servo"] }

[patch.crates-io]
tikv-jemalloc-sys = { path = "../../crates/vendor/tikv-jemalloc-sys" }
stylo_derive = { path = "../../patches/stylo_derive-0.21.0" }
zed-font-kit = { path = "../../patches/zed-font-kit-0.14.1-zed" }
