[package]
name = "servokit"
version = "0.1.0"
edition = "2021"
publish = false

[[example]]
name = "multiple-native-views"
path = "examples/multiple-native-views/main.rs"
required-features = ["servo"]

[features]
default = []
macos-system-webview = ["servo", "dep:objc2", "dep:objc2-app-kit", "dep:wry"]
servo = [
    "dep:cocoa",
    "dep:core-foundation",
    "dep:core-video",
    "dep:dpi",
    "dep:euclid",
    "dep:gleam",
    "dep:glow",
    "dep:image",
    "dep:io-surface",
    "dep:objc2-core-foundation",
    "dep:raw-window-handle",
    "dep:servo",
    "dep:surfman",
    "dep:webrender_api",
    "servokit-embedder/servo",
]

[dependencies]
servokit-embedder = { path = "../servokit-embedder" }
servokit-host = { path = "../servokit-host" }

[target.'cfg(any(target_os = "android", target_os = "macos", target_os = "windows", target_os = "linux"))'.dependencies]
dpi = { workspace = true, optional = true }
raw-window-handle = { workspace = true, optional = true }
servo = { workspace = true, optional = true }
webrender_api = { workspace = true, optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = { workspace = true, optional = true }
core-foundation = { workspace = true, optional = true }
core-video = { workspace = true, optional = true }
euclid = { workspace = true, optional = true }
gleam = { workspace = true, optional = true }
glow = { workspace = true, optional = true }
image = { workspace = true, optional = true }
io-surface = { workspace = true, optional = true }
objc2-core-foundation = { workspace = true, optional = true }
objc2-app-kit = { workspace = true, optional = true }
objc2 = { workspace = true, optional = true }
surfman = { workspace = true, optional = true }
wry = { workspace = true, optional = true }
